[project]
name = "elomimic-api"
version = "0.1.0"
description = "HTTP API for elomimic"
readme = "README.md"
authors = [
    { name = "ThamiEngineering", email = "developer@thami.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "chess>=1.11.2",
    "fastapi[standard]>=0.141.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.0",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[tool.fastapi]
entrypoint = "elomimic_api.main:app"

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
extend-select = ["I"]